MODEL_NAME="llama3.2:3b"
OLLAMA_SERVER_URL="http://localhost:11434"
DOWNLOADS_PATH="downloads"
LLM_CHUNK_SIZE=2500
LLM_CHUNK_OVERLAP=300
TEMPERATURE=0.1
CONCURRENCY_LEVEL=4
TIMEOUT=120
LOG_FILE = "logs/summarizer.log"
MODEL_PATH = "/app1/python/code/chatbot/nlp_models/t5_small_model"
NLP_CHUNK_SIZE=800
NLP_CHUNK_OVERLAP=200
NLP_MODEL_MAX_LENGTH=512
NLP_CHUNK_OUTOUT_MIN_LENGTH=40
NLP_CHUNK_OUTOUT_MAX_LENGTH=150
VECTOR_DB_PATH = "/app1/python/code/chatbot/vectordb/"
# EMBEDDING_MODEL_PATH = "/app1/python/code/document_summarizer_with_nlp/embedding_model/all_mini_lm2/"
EMBEDDING_MODEL_PATH = "/app1/python/code/chatbot/embedding_model/instructor_base/"
EMBEDDING_CHUNK_SIZE=500
EMBEDDING_CHUNK_OVERLAP=100